//Test Script
/*
Integer fnumber = 5;
Integer factorial = 1;
    
    for (Integer i = 1; i <= fnumber; i++) {
        factorial *= i;
    }
    
    System.debug(factorial);

*/
PLACEHOLDER
public class CustomException extends Exception {}

try {
    Integer fnumber = 5;
    Integer expectedFactorial = 120;      
    Integer factorial = 1;
    for (Integer i = 1; i <= fnumber; i++) {
        factorial *= i;
    }
    
    System.assertEquals(expectedFactorial, factorial);

} catch (Exception exc) {
    throw new CustomException('There is an error: ' + exc.getMessage());
}
